### ISSUE TITLE
Setting STATAMIC_GIT_ENABLED to false in .env causes Exception

### ISSUE THREAD

**Issue by AdD959** [aerni/statamic-dynamic-cache#5]
I found that when setting STATAMIC_GIT_ENABLED to _false_ in the .env file, a "Statamic Git integration is currently disabled" Exception occurs. 

**Replication Steps**

1. install Dynamic Cache via composer whilst STATAMIC_GIT_ENABLED = true
2. Use Dynamic Cache functionality (? maybe required or not)
3. set STATAMIC_GIT_ENABLED = false
4. Attempt to access pages or CP results in error (see below). Artisan/please seems to break too.

![Screenshot 2022-02-14 at 16 09 15](https://user-images.githubusercontent.com/35370666/153903754-52b2fe07-b04d-4b8c-b7e9-317c38d17f8d.png)

**Comment by aerni** [comment]
Good catch! Fixed with [v1.1.1](https://github.com/aerni/statamic-dynamic-cache/releases/tag/v1.1.1).
