### ISSUE TITLE
v1.1.1 causes composer install issue

### ISSUE THREAD

**Issue by AdD959** [aerni/statamic-dynamic-cache#6]
Just have one more issue. Composer install v1.1.1 causes a database connection [] not configured exception if no database is configured. In my case, my site has no database.

**Replication steps**

1. Set DB_CONNECTION in .env to empty or null
2. Upgrade Dynamic Cache addon via CP or composer to v1.1.1
3. See produced error below

<img width="1120" alt="Screenshot 2022-02-14 at 22 18 31" src="https://user-images.githubusercontent.com/35370666/153957422-dd92de82-fba3-4de1-bf94-6222a1991da1.png">

**Comment by aerni** [comment]
That's not an issue with this addon per se. Just leave `DB_CONNECTION=mysql`. It defaults to that anyways in `config/database.php`.
