### ISSUE TITLE
Question: Is this necessary for half caching?

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-dynamic-cache#7]
Is a solution like this is required for forms and dynamic sections (e.g. filtered entries) when using the half caching method? You mention full caching specifically in the docs.

Thanks!

**Comment by aerni** [comment]
That's correct. Forms and other dynamic features such as `sort="random"` don't work with any type of [static caching](https://statamic.dev/static-caching). This addon simply helps to dynamically update the configuration, so you don't have to.

**Comment by stuartcusackie** [comment]
I wonder if this new `no_cache` tag negates the need to exclude entire pages from the static cache...
https://github.com/statamic/cms/pull/5575

**Comment by aerni** [comment]
Yes, that's what this tag is for.
